### ISSUE TITLE
[TimeSpeed] Allow Time to Pass in Saloon

### ISSUE THREAD

**Issue by vorpalhex** [cantorsdust/TimeSpeed#1]
Often times a good way to kill time and wait to catch several NPCs at the end of the day is to hang out in the saloon. An option to allow time to pass (and at a configurable rate) in the Saloon would be awesome.

As a possible extension, could we extend so that any location could be configured? It seems all that's needed is a location name and a desired tick rate.

**Comment by Pathoschild** [comment]
@vorpalhex This ticket is pretty old, but that's supported now. You can do this in the `config.json`:

```js
"TickLengthByLocation": {
    "Indoors": null, // freeze time
    "Saloon": 14 // default time
  }
```
See the [readme](https://github.com/cantorsdust/StardewMods/tree/master/TimeSpeed#use) for more info.
