### ISSUE TITLE
A stop sign

### ISSUE THREAD

**Issue by FarmingApple** [cantorsdust/TimeSpeed#12]
Numbers no longer blink when they stop. Is it new version? Or am I wrong? I can't tell if it's stopped or not. If it's new, I'd like it to blink again. I would like to ask you a sincere favor.

**Comment by Pathoschild** [comment]
The number blinking seems to work fine in the latest versions of TimeSpeed and Stardew Valley, so I'll mark this fixed. Feel free to comment if it still doesn't work for you though.
