### ISSUE TITLE
[AllProfessions] Crab pots not producing trash

### ISSUE THREAD

**Issue by ghost** [cantorsdust/TimeSpeed#22]
Currently I have my config set to ignore the "Mariner" profession as I still desire trash to be caught. This setting is not being honored however as none has been caught in over two in-game weeks.

![Screenshot_20220224_183831](https://user-images.githubusercontent.com/4485158/155832516-60eca926-3028-464a-9560-5e623751d3db.png)

Could be a result of another mod but the only mods that do anything skill related are Luck Skill and Cooking Skill, both of which are supported as far as I understand?

```
Cooking Skill: see SpaceCore.
Luck Skill: see SpaceCore.
SpaceCore: auto-detects if you have All Professions and adds its custom professions.
(Customizing All Professions' assets/data.json has no effect for SpaceCore professions.)
```

Perhaps the issue is that this mod does not support retroactive changes? If this is the case then maybe the default should be set to not touch skills until they are configured or simply exclude Mariner unless explicitly enabled?

On an semi-unrelated note: I saw that this [commit](https://github.com/cantorsdust/StardewMods/commit/5d4a8e9b0b68b9bc50080024641620afd05eb967) fixed the Generic Mod Config being inverted when editing in game. Hope this releases soon as having to relaunch the game when manually editing the config file makes testing really tedious (especially with SVE that takes 5 minutes to load).

**Comment by Pathoschild** [comment]
Hi! The config UI changes which professions are added when you reach the required level. If you already have the profession, it won't retroactively unlearn it; I'll add a note in the next version to clarify that. You can use [CJB Cheats Menu](https://www.nexusmods.com/stardewvalley/mods/4) to view and edit your learned professions though.

There's no firm release date, but I'll probably be releasing that update within the next few days.

**Comment by ghost** [comment]
Thanks and no worries. I edited my save file manually to revert the change.
