### ISSUE TITLE
Newer SMAPI Support

### ISSUE THREAD

**Issue by Xaekai** [cantorsdust/TimeSpeed#4]
Do you intend on updating this anytime soon?

**Comment by cantorsdust** [comment]
No. I'm in medical residency working 80 hours a week for the next 3 years
and then hopefully fellowship working 80 hours a week for 4 years after
that.

If others want this mod updated, they're free to take the source and do
whatever they like with it.

**Comment by Xaekai** [comment]
Thank you for taking the time to respond.
