### ISSUE TITLE
[TimeSpeed] Key Combinations

### ISSUE THREAD

**Issue by KainMorgen** [cantorsdust/TimeSpeed#9]
Is it possible to configure the inputs for the timespeeds to be key combinations with LeftControl for example?
I'm thinking about using this for a little slower gameplay in multiplayer because time doesnt stop there when using containers but I would like to accidentally change the setting if I ever use the ingame chat.

I tried this within config.json but it has no effect.
LeftControl itself should be recognized by the game. Therefore I guess I just putting AND there won't make TimeSpeed check if all buttons are pressed.

"Keys": {
"FreezeTime": "LeftControl" AND "N",
"IncreaseTickInterval": "LeftControl" AND "OemPeriod",
"DecreaseTickInterval": "LeftControl" AND "OemComma",
"ReloadConfig": "LeftControl" AND "B"
}

**Comment by Pathoschild** [comment]
Done in the upcoming TimeSpeed 2.5 using SMAPI's new [multi-key bindings](https://stardewvalleywiki.com/Modding:Player_Guide/Key_Bindings#Multi-key_bindings). Thanks for the suggestion!

The format for your example would be:
```js
"Keys": {
    "FreezeTime": "LeftControl + N",
    "IncreaseTickInterval": "LeftControl + OemPeriod",
    "DecreaseTickInterval": "LeftControl + OemComma",
    "ReloadConfig": "LeftControl + B"
}
```
